### ISSUE TITLE
.so version of encrypt.dll so the bot can be used under Linux and Mac

### ISSUE THREAD

**Issue by davidsun** [NECROBOTIO/NecroBot-Rocket-API#12]

**Comment by M132** [comment]
What is this encrypt thing and where is it's source?

**Comment by davidsun** [comment]
@M132 I don't think that they've open sourced it (I might be wrong). You can see encrypt32.dll and encrypt64.dll under the root folder of the project.

**Comment by M132** [comment]
They have to open-source it, or change license, because closed-source libraries violate GPLv3.

**Comment by Gh0stN00b** [comment]
As I remember, they cant open source it, it is copyrighted

**Comment by davidsun** [comment]
I see. Yeah, I don't know whether it can be open sourced but at least there should be a .so file?

**Comment by Gh0stN00b** [comment]
No they cant, still the same issue, copyrighted, they remove the unknown6 repo because of that

**Comment by davidsun** [comment]
Hmm okay, that sort of makes sense. I guess we have to live with it then.

Just an extra question, our of curiosity - who owns the copyright? Is that the company, or an individual?

**Comment by Gh0stN00b** [comment]
Niantic

**Comment by davidsun** [comment]
Got it. I'll close the issue.
