### ISSUE TITLE
RequestBuilder.Encrypt memory leak?

### ISSUE THREAD

**Issue by darkxor** [NECROBOTIO/NecroBot-Rocket-API#13]
Seems like RequestBuilder.Encrypt lacks Marshal.FreeHGlobal calls.
Sorry dont know how to add pull request so just added issue.

**Comment by NecronomiconCoding** [comment]
https://github.com/NECROBOTIO/NecroBot-Rocket-API/commit/05774bc876a07b4832792a2504b8ee6e0f5a3d0c
