### ISSUE TITLE
Typo in RequestBuilder

### ISSUE THREAD

**Issue by Lennix** [NECROBOTIO/NecroBot-Rocket-API#14]
https://github.com/NECROBOTIO/NecroBot-Rocket-API/blob/2b579be577bbe452dac08e4a5ccedb727da3fc6d/PokemonGo.RocketAPI/Helpers/RequestBuilder.cs#L51

You might want to fix that.

**Comment by NecronomiconCoding** [comment]
https://github.com/NECROBOTIO/NecroBot-Rocket-API/commit/2054443fc775229b864211ce31aaf17432b7a203
