### ISSUE TITLE
what happened?

### ISSUE THREAD

**Issue by GamingMaster777** [NECROBOTIO/NecroBot-Rocket-API#7]
where did all the other issues go? is the pokestopo issue fixed?

**Comment by tufan123** [comment]
I don't think so. I still get no pokestops to visit error.

**Comment by bodycount1982** [comment]
ok so its not just me. I thought I was going crazy or had some info wrong. Hopefully they will have the no pokestops in area error fixed soon

**Comment by FAumeier** [comment]
See [https://www.reddit.com/r/pokemongodev/comments/4w1cvr/pokemongo_current_api_status/?ref=share&ref_source=link](https://www.reddit.com/r/pokemongodev/comments/4w1cvr/pokemongo_current_api_status/?ref=share&ref_source=link) for info.
